package Inicio;

import java.awt.BorderLayout;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author SAMIR
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {        
        initComponents();
        principal p1 = new principal();
        ShowPanel(p1);        
        setIconImage(new ImageIcon(getClass().getResource("/img/balon.png")).getImage());
    }
    
    private void ShowPanel (JPanel p){
        p.setSize(1000, 710);
        p.setLocation(0, 0);
        
        content.removeAll();
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        DashBoard = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        btnReservas = new javax.swing.JButton();
        btnMisReservas = new javax.swing.JButton();
        btnPreguntas = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        content = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        btnInicio2 = new javax.swing.JButton();
        btnReservarCampo = new javax.swing.JButton();
        btnContacto = new javax.swing.JButton();
        btnMisReservas2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");

        BG.setBackground(new java.awt.Color(255, 255, 255));
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DashBoard.setBackground(new java.awt.Color(51, 102, 255));
        DashBoard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/casa.png"))); // NOI18N
        jLabel1.setToolTipText("");
        DashBoard.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cita.png"))); // NOI18N
        DashBoard.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/recepcion.png"))); // NOI18N
        DashBoard.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ayudar.png"))); // NOI18N
        DashBoard.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/apagar.png"))); // NOI18N
        DashBoard.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, -1, -1));

        btnInicio.setBackground(new java.awt.Color(51, 102, 255));
        btnInicio.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("HOME");
        btnInicio.setBorderPainted(false);
        btnInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DashBoard.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 60));

        btnReservas.setBackground(new java.awt.Color(51, 102, 255));
        btnReservas.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnReservas.setForeground(new java.awt.Color(255, 255, 255));
        btnReservas.setText("RESERVAS");
        btnReservas.setBorderPainted(false);
        btnReservas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DashBoard.add(btnReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 200, 60));

        btnMisReservas.setBackground(new java.awt.Color(51, 102, 255));
        btnMisReservas.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnMisReservas.setForeground(new java.awt.Color(255, 255, 255));
        btnMisReservas.setText("MIS RESERVAS");
        btnMisReservas.setBorderPainted(false);
        btnMisReservas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DashBoard.add(btnMisReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 200, 60));

        btnPreguntas.setBackground(new java.awt.Color(51, 102, 255));
        btnPreguntas.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnPreguntas.setForeground(new java.awt.Color(255, 255, 255));
        btnPreguntas.setText("PREGUNTAS");
        btnPreguntas.setBorderPainted(false);
        btnPreguntas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPreguntas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreguntasActionPerformed(evt);
            }
        });
        DashBoard.add(btnPreguntas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 200, 60));

        jButton9.setBackground(new java.awt.Color(51, 102, 255));
        jButton9.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("SALIR");
        jButton9.setBorderPainted(false);
        jButton9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        DashBoard.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 200, 90));

        BG.add(DashBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 200, 710));

        content.setBackground(new java.awt.Color(204, 255, 255));
        content.setMaximumSize(new java.awt.Dimension(1000, 590));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        BG.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 1000, 590));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SJL.png"))); // NOI18N
        BG.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btnInicio2.setText("Inicio");
        BG.add(btnInicio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, -1, -1));

        btnReservarCampo.setText("Reservar Campo");
        BG.add(btnReservarCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 30, 120, -1));

        btnContacto.setText("Contacto");
        BG.add(btnContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 30, -1, -1));

        btnMisReservas2.setText("Mis Reservas");
        BG.add(btnMisReservas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPreguntasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreguntasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPreguntasActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        System.exit(0);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ini().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JPanel DashBoard;
    private javax.swing.JButton btnContacto;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnInicio2;
    private javax.swing.JButton btnMisReservas;
    private javax.swing.JButton btnMisReservas2;
    private javax.swing.JButton btnPreguntas;
    private javax.swing.JButton btnReservarCampo;
    private javax.swing.JButton btnReservas;
    private javax.swing.JPanel content;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
