package Inicio;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author SAMIR
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {        
        initComponents();
        reservas p1 = new reservas();
        ShowPanel(p1);        
    }
    
    private void ShowPanel (JPanel p){
        p.setSize(1000, 710);
        p.setLocation(0, 0);
        
        content.removeAll();
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        DashBoard = new javax.swing.JPanel();
        btnInicio = new javax.swing.JLabel();
        btnReservas = new javax.swing.JLabel();
        btnPreguntas = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");

        BG.setBackground(new java.awt.Color(255, 255, 255));
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DashBoard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInicio.setBackground(new java.awt.Color(51, 102, 255));
        btnInicio.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnInicio.setText("INICIO");
        btnInicio.setOpaque(true);
        DashBoard.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 200, 60));

        btnReservas.setBackground(new java.awt.Color(51, 102, 255));
        btnReservas.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnReservas.setForeground(new java.awt.Color(255, 255, 255));
        btnReservas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnReservas.setText("RESERVAS");
        btnReservas.setOpaque(true);
        DashBoard.add(btnReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 200, 60));

        btnPreguntas.setBackground(new java.awt.Color(51, 102, 255));
        btnPreguntas.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnPreguntas.setForeground(new java.awt.Color(255, 255, 255));
        btnPreguntas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPreguntas.setText("PREGUNTAS");
        btnPreguntas.setOpaque(true);
        DashBoard.add(btnPreguntas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 200, 60));

        BG.add(DashBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 800));

        content.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );

        BG.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 1000, 710));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SJL.png"))); // NOI18N
        BG.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ini().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JPanel DashBoard;
    private javax.swing.JLabel btnInicio;
    private javax.swing.JLabel btnPreguntas;
    private javax.swing.JLabel btnReservas;
    private javax.swing.JPanel content;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
