package Inicio;


import java.sql.SQLException;
import OBJETS.USUARIO;
import OBJETS.UsuarioDAO;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author SAMIR
 */
public class registrar extends javax.swing.JPanel {
    
    private UsuarioDAO usuarioDAO;

    
    public registrar() {
        usuarioDAO = new UsuarioDAO();
        initComponents();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        Panel1 = new javax.swing.JPanel();
        txtDNI = new javax.swing.JTextField();
        Panel2 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        Panel3 = new javax.swing.JPanel();
        txtPass = new javax.swing.JTextField();
        RegistrarPanel = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JLabel();

        BG.setBackground(new java.awt.Color(255, 255, 255));
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(94, 94, 96));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("REGISTRAR");
        Header.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 60));

        BG.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 60));

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        BG.add(Panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 70, 50));

        txtDNI.setForeground(new java.awt.Color(111, 111, 111));
        txtDNI.setText("Ingrese su DNI");
        txtDNI.setToolTipText("");
        txtDNI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        txtDNI.setSelectionColor(new java.awt.Color(0, 153, 204));
        txtDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDNIKeyPressed(evt);
            }
        });
        BG.add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 330, 50));

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        BG.add(Panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 70, 50));

        txtNombre.setForeground(new java.awt.Color(111, 111, 111));
        txtNombre.setText("Ingrese su Nombre");
        txtNombre.setToolTipText("");
        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        txtNombre.setSelectionColor(new java.awt.Color(0, 153, 204));
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
        });
        BG.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 330, 50));

        javax.swing.GroupLayout Panel3Layout = new javax.swing.GroupLayout(Panel3);
        Panel3.setLayout(Panel3Layout);
        Panel3Layout.setHorizontalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        Panel3Layout.setVerticalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        BG.add(Panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        txtPass.setForeground(new java.awt.Color(111, 111, 111));
        txtPass.setText("Ingrese su Contraseña");
        txtPass.setToolTipText("");
        txtPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        txtPass.setSelectionColor(new java.awt.Color(0, 153, 204));
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassKeyPressed(evt);
            }
        });
        BG.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 330, 50));

        RegistrarPanel.setBackground(new java.awt.Color(0, 150, 94));
        RegistrarPanel.setPreferredSize(new java.awt.Dimension(200, 50));

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegistrar.setText("Registrar");
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRegistrarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout RegistrarPanelLayout = new javax.swing.GroupLayout(RegistrarPanel);
        RegistrarPanel.setLayout(RegistrarPanelLayout);
        RegistrarPanelLayout.setHorizontalGroup(
            RegistrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        RegistrarPanelLayout.setVerticalGroup(
            RegistrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        BG.add(RegistrarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 400, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    
    private void txtDNIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDNIKeyPressed
        if (txtDNI.getText().equals("Ingrese su DNI")){
            txtDNI.setText("");
            txtDNI.setForeground(Color.black);
        }
        if(String.valueOf(txtPass.getText()).isEmpty()){
            txtPass.setText("Ingrese su Contraseña");
            txtPass.setForeground(new Color(111, 111, 111));
        }
        if (txtNombre.getText().isEmpty()){
            txtNombre.setText("Ingrese su Nombre");
            txtNombre.setForeground(new Color(111, 111, 111));
        }
    }//GEN-LAST:event_txtDNIKeyPressed
    
    JPanel panel;
    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
                
        
                String dni = txtDNI.getText();
                String nombre = txtNombre.getText();
                String password = txtPass.getText();

                USUARIO usuario = new USUARIO(dni, nombre, password);
                try {
                    usuarioDAO.registerUsuario(usuario);
                    JOptionPane.showMessageDialog(panel, "Usuario registrado exitosamente!");
                } catch (SQLException throwables) {
                    throwables.printStackTrace();
                    JOptionPane.showMessageDialog(panel, "Error al registrar el usuario.");
                }
    }//GEN-LAST:event_btnRegistrarMouseClicked

    private void btnRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseExited
        RegistrarPanel.setBackground(new Color(0, 150, 94));
    }//GEN-LAST:event_btnRegistrarMouseExited

    private void btnRegistrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMousePressed
        RegistrarPanel.setBackground(new Color(0, 102, 51));
    }//GEN-LAST:event_btnRegistrarMousePressed

    private void txtPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyPressed
        if (txtPass.getText().equals("Ingrese su Contraseña")){
            txtPass.setText("");
            txtPass.setForeground(Color.black);
        }
        if (txtDNI.getText().isEmpty()){
            txtDNI.setText("Ingrese su DNI");
            txtDNI.setForeground(new Color(111, 111, 111));
        }
        if (txtNombre.getText().isEmpty()){
            txtNombre.setText("Ingrese su Nombre");
            txtNombre.setForeground(new Color(111, 111, 111));
        }
    }//GEN-LAST:event_txtPassKeyPressed

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        if (txtNombre.getText().equals("Ingrese su Nombre")){
            txtNombre.setText("");
            txtNombre.setForeground(Color.black);
        }
        if (txtDNI.getText().isEmpty()){
            txtDNI.setText("Ingrese su DNI");
            txtDNI.setForeground(new Color(111, 111, 111));
        }
        if (txtPass.getText().isEmpty()){
            txtPass.setText("Ingrese su Contraseña");
            txtPass.setForeground(new Color(111, 111, 111));
        }
    }//GEN-LAST:event_txtNombreKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2;
    private javax.swing.JPanel Panel3;
    private javax.swing.JPanel RegistrarPanel;
    private javax.swing.JLabel btnRegistrar;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPass;
    // End of variables declaration//GEN-END:variables
}
